### ISSUE TITLE
[Ver. 4.2.0] Class 'Illuminate\Support\Facades\Http' not found

### ISSUE THREAD

**Issue by EdisonJwa** [bs-community/yggdrasil-api#27]
`Details: Class 'Illuminate\Support\Facades\Http' not found`

Log File  `storage/logs/laravel-2020-03-09.log` 

```
[2020-03-09 20:15:50] production.ERROR: Class 'Illuminate\Support\Facades\Http' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Illuminate\\Support\\Facades\\Http' not found at /var/www/skin-server/plugins/yggdrasil-api/src/Models/Profile.php:177)
[stacktrace]
#0 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Support/helpers.php(521): Yggdrasil\\Models\\Profile->Yggdrasil\\Models\\{closure}()
#1 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(105): value()
#2 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(357): Illuminate\\Cache\\Repository->get()
#3 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Cache\\CacheManager->__call()
#4 /var/www/skin-server/plugins/yggdrasil-api/src/Models/Profile.php(189): Illuminate\\Support\\Facades\\Facade::__callStatic()
#5 /var/www/skin-server/plugins/yggdrasil-api/src/Models/Profile.php(89): Yggdrasil\\Models\\Profile->fetchProfileFromMojang()
#6 /var/www/skin-server/plugins/yggdrasil-api/src/Controllers/ProfileController.php(22): Yggdrasil\\Models\\Profile->serialize()
#7 [internal function]: Yggdrasil\\Controllers\\ProfileController->getProfileFromUuid()
#8 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#9 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#10 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#11 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#12 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#13 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#14 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#16 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#17 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()
#18 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#19 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#20 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#21 /var/www/skin-server/plugins/yggdrasil-api/src/Middleware/AddApiIndicationHeader.php(11): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Yggdrasil\\Middleware\\AddApiIndicationHeader->handle()
#23 /var/www/skin-server/app/Http/Middleware/DetectLanguagePrefer.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\DetectLanguagePrefer->handle()
#25 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/skin-server/app/Http/Middleware/ConvertEmptyStringsToNull.php(23): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#27 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#28 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#30 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#32 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#34 /var/www/skin-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#35 /var/www/skin-server/public/index.php(48): Illuminate\\Foundation\\Http\\Kernel->handle()
#36 {main}
"}
```

**Comment by g-plane** [comment]
如果你在使用 BS v5，请将 BS 和此插件升级到最新版本。
