### ISSUE TITLE
[bug] 2.1.6版本无法登录

### ISSUE THREAD

**Issue by cqjjjzr** [bs-community/yggdrasil-api#5]
Verbose日志：
```log
[2018-07-29 21:51:47] production.ERROR: ErrorException: Undefined property: stdClass::$column_name in C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\MySqlProcessor.php:18
Stack trace:
#0 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\MySqlProcessor.php(18): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined prope...', 'C:\\blessingskin...', 18, Array)
#1 [internal function]: Illuminate\Database\Query\Processors\MySqlProcessor->Illuminate\Database\Query\Processors\{closure}(Object(stdClass))
#2 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\MySqlProcessor.php(21): array_map(Object(Closure), Array)
#3 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Database\Schema\MySqlBuilder.php(40): Illuminate\Database\Query\Processors\MySqlProcessor->processColumnListing(Array)
#4 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php(69): Illuminate\Database\Schema\MySqlBuilder->getColumnListing('users')
#5 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(219): Illuminate\Database\Schema\Builder->hasColumn('users', 'verified')
#6 C:\blessingskinserver\plugins\yggdrasil-api\src\Controllers\AuthController.php(277): Illuminate\Support\Facades\Facade::__callStatic('hasColumn', Array)
#7 C:\blessingskinserver\plugins\yggdrasil-api\src\Controllers\AuthController.php(29): Yggdrasil\Controllers\AuthController->checkUserCredentials(Object(Illuminate\Http\Request))
#8 [internal function]: Yggdrasil\Controllers\AuthController->authenticate(Object(Illuminate\Http\Request))
#9 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(80): call_user_func_array(Array, Array)
#10 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('authenticate', Array)
#11 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(Yggdrasil\Controllers\AuthController), Object(Illuminate\Routing\Route), 'authenticate')
#12 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Yggdrasil\Controllers\AuthController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'authenticate')
#18 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Yggdrasil\\Contr...', 'authenticate')
#19 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#20 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 C:\blessingskinserver\plugins\yggdrasil-api\src\Middleware\Throttle.php(22): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 [internal function]: Yggdrasil\Middleware\Throttle->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 C:\blessingskinserver\plugins\yggdrasil-api\src\Middleware\CheckContentType.php(16): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 [internal function]: Yggdrasil\Middleware\CheckContentType->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#31 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 C:\blessingskinserver\app\Http\Middleware\AfterSessionBooted.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: App\Http\Middleware\AfterSessionBooted->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#41 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#43 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#46 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#48 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#51 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#53 C:\blessingskinserver\app\Http\Middleware\RedirectIfUrlEndsWithSlash.php(22): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 [internal function]: App\Http\Middleware\RedirectIfUrlEndsWithSlash->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#56 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#58 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#61 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#63 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#64 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#65 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#66 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#67 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#68 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#69 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#70 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#71 C:\blessingskinserver\app\Http\Middleware\DetectLanguagePrefer.php(12): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#72 [internal function]: App\Http\Middleware\DetectLanguagePrefer->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#74 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#76 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#77 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#78 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#79 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#80 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#81 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#82 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#83 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#84 C:\blessingskinserver\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#85 C:\blessingskinserver\bootstrap\kernel.php(19): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#86 C:\blessingskinserver\index.php(30): require('C:\\blessingskin...')
#87 {main}  

```

**Comment by prinsss** [comment]
了解了，这确实是 Bug，感谢反馈。https://github.com/laravel/framework/issues/20190

请尝试将 https://github.com/bs-community/yggdrasil-api/blob/master/src/Controllers/AuthController.php#L277 文件的第 277 - 281 行由：

```
if (Schema::hasColumn('users', 'verified')) {
    if (option('require_verification') && !$user->verified) {
        // 原内容
    }
}
```

修改为：

```
if (option('require_verification') && $user->verified === false) {
    // 原内容
}
```
